import { KPIDefinition } from '@/types'

export const KPI_DICTIONARY: KPIDefinition[] = [
  {
    slug: 'revenue_mtd',
    name: 'Revenue MTD',
    category: 'revenue',
    definition: 'Total recognized revenue from all invoices in the current month to date.',
    calculationNotes: 'SUM(invoice.amount) WHERE invoice.status IN (paid, open) AND invoice.invoice_date >= month_start AND invoice.invoice_date <= today. Excludes void and credited invoices.',
    grain: 'Daily rollup',
    filters: ['date_range', 'market', 'branch', 'vertical'],
    primarySource: 'Billing/ERP',
    secondarySources: ['CRM (for account mapping)'],
    refreshCadence: 'Every 4 hours',
    owner: 'Finance - Controller',
    reconciliationTarget: 'Invoice table sum should match within 0.1%',
    dataQualityChecks: ['No duplicate invoice numbers', 'All invoices have valid account mapping', 'Invoice dates within expected range'],
    drillPath: '/kpi/revenue_mtd → by market → by branch → by account → invoice detail',
    format: 'currency',
    higherIsBetter: true,
  },
  {
    slug: 'pipeline_30_60_90',
    name: 'Pipeline 30/60/90',
    category: 'sales',
    definition: 'Total opportunity value segmented by expected close date: 0-30 days, 31-60 days, 61-90 days.',
    calculationNotes: 'SUM(opportunity.amount * opportunity.probability) WHERE opportunity.stage NOT IN (closed_won, closed_lost) GROUP BY close_date bucket.',
    grain: 'Daily snapshot',
    filters: ['close_date_range', 'market', 'branch', 'owner', 'stage'],
    primarySource: 'CRM (Salesforce)',
    secondarySources: [],
    refreshCadence: 'Every 2 hours',
    owner: 'Sales Ops - Director',
    reconciliationTarget: 'Sum of weighted pipeline should match opportunity list total',
    dataQualityChecks: ['Close dates not in past for open opps', 'Probability matches stage', 'Owner assigned for all opps'],
    drillPath: '/kpi/pipeline_30_60_90 → by time bucket → by stage → opportunity list → opportunity detail',
    format: 'currency',
    higherIsBetter: true,
  },
  {
    slug: 'win_rate',
    name: 'Win Rate',
    category: 'sales',
    definition: 'Percentage of opportunities that closed as won out of all opportunities that closed (won + lost) in the period.',
    calculationNotes: 'COUNT(closed_won) / COUNT(closed_won + closed_lost) for opportunities with close_date in period.',
    grain: 'Monthly rollup',
    filters: ['date_range', 'market', 'branch', 'owner', 'vertical'],
    primarySource: 'CRM (Salesforce)',
    secondarySources: [],
    refreshCadence: 'Daily',
    owner: 'Sales Ops - Director',
    reconciliationTarget: 'Win rate calculated from closed opp counts should match',
    dataQualityChecks: ['Lost reason populated for lost opps', 'No opps closed without stage history', 'Stage transitions logged'],
    drillPath: '/kpi/win_rate → by market → by owner → won/lost breakdown → opportunity detail',
    format: 'percent',
    higherIsBetter: true,
    target: 0.35,
    warningThreshold: 0.28,
    criticalThreshold: 0.20,
  },
  {
    slug: 'avg_cycle_time_days',
    name: 'Avg Sales Cycle (Days)',
    category: 'sales',
    definition: 'Average number of days from opportunity creation to close for won opportunities.',
    calculationNotes: 'AVG(close_date - created_date) WHERE stage = closed_won AND close_date in period.',
    grain: 'Monthly rollup',
    filters: ['date_range', 'market', 'branch', 'owner', 'deal_size_tier'],
    primarySource: 'CRM (Salesforce)',
    secondarySources: [],
    refreshCadence: 'Daily',
    owner: 'Sales Ops - Director',
    reconciliationTarget: 'Manual calculation from opp list should match',
    dataQualityChecks: ['Created date <= close date', 'No negative cycle times', 'Stage history complete'],
    drillPath: '/kpi/avg_cycle_time_days → by market → by deal size → opportunity list',
    format: 'days',
    higherIsBetter: false,
    target: 45,
    warningThreshold: 60,
    criticalThreshold: 90,
  },
  {
    slug: 'forecast_revenue_8w',
    name: 'Forecast Revenue (8 Weeks)',
    category: 'revenue',
    definition: 'Projected revenue for the next 8 weeks based on weighted pipeline, historical conversion rates, and seasonality adjustments.',
    calculationNotes: 'SUM(pipeline.weighted_amount) + baseline_recurring_revenue + seasonality_adjustment. Uses last 12-week conversion rates by stage.',
    grain: 'Weekly projection',
    filters: ['market', 'branch', 'scenario'],
    primarySource: 'CRM (Salesforce)',
    secondarySources: ['Billing/ERP (historical patterns)', 'Workforce/HR (capacity constraints)'],
    refreshCadence: 'Weekly (Monday 6am)',
    owner: 'Finance - FP&A',
    reconciliationTarget: 'Backtest MAE should be < 8%',
    dataQualityChecks: ['All open opps have valid close dates', 'Probability aligned with stage', 'Historical data complete'],
    drillPath: '/forecast → scenario toggle → assumptions → backtest → pipeline detail',
    format: 'currency',
    higherIsBetter: true,
  },
  {
    slug: 'variance_to_target_mtd',
    name: 'Variance to Target MTD',
    category: 'revenue',
    definition: 'Difference between actual revenue MTD and the prorated monthly target.',
    calculationNotes: '(Revenue_MTD - (Monthly_Target * days_elapsed / days_in_month)) / (Monthly_Target * days_elapsed / days_in_month).',
    grain: 'Daily',
    filters: ['market', 'branch'],
    primarySource: 'Billing/ERP',
    secondarySources: ['Planning (targets)'],
    refreshCadence: 'Every 4 hours',
    owner: 'Finance - Controller',
    reconciliationTarget: 'Target from planning system should match',
    dataQualityChecks: ['Targets loaded for all markets', 'No missing daily revenue data'],
    drillPath: '/kpi/variance_to_target_mtd → variance drivers → by market → by revenue type',
    format: 'percent',
    higherIsBetter: true,
    target: 0,
    warningThreshold: -0.05,
    criticalThreshold: -0.10,
  },
  {
    slug: 'service_risk_index',
    name: 'Service Risk Index',
    category: 'operations',
    definition: 'Composite score (0-100) measuring service delivery risk based on callbacks, missed services, complaints, and response time.',
    calculationNotes: '100 - (callback_rate * 25 + missed_rate * 30 + complaint_rate * 25 + response_time_penalty * 20). Higher is better.',
    grain: 'Daily rollup',
    filters: ['market', 'branch', 'route', 'technician'],
    primarySource: 'PestPac/Field Service',
    secondarySources: ['CRM (complaints)', 'Workforce/HR (capacity)'],
    refreshCadence: 'Every 2 hours',
    owner: 'Operations - VP',
    reconciliationTarget: 'Component metrics should sum to index',
    dataQualityChecks: ['All service events have status', 'Technician assigned', 'Time-on-site reasonable'],
    drillPath: '/kpi/service_risk_index → component breakdown → by branch → at-risk accounts',
    format: 'index',
    higherIsBetter: true,
    target: 85,
    warningThreshold: 75,
    criticalThreshold: 65,
  },
  {
    slug: 'callback_rate',
    name: 'Callback Rate',
    category: 'operations',
    definition: 'Percentage of completed service visits that required a callback within 14 days.',
    calculationNotes: 'COUNT(callbacks) / COUNT(completed_services) WHERE callback.date <= original.completed_date + 14 days.',
    grain: 'Weekly rollup',
    filters: ['date_range', 'market', 'branch', 'route', 'technician', 'service_type'],
    primarySource: 'PestPac/Field Service',
    secondarySources: [],
    refreshCadence: 'Daily',
    owner: 'Operations - Director',
    reconciliationTarget: 'Callback count / service count should match',
    dataQualityChecks: ['Callbacks linked to original service', 'Service dates valid', 'Technician assigned'],
    drillPath: '/kpi/callback_rate → by branch → by technician → service event detail',
    format: 'percent',
    higherIsBetter: false,
    target: 0.05,
    warningThreshold: 0.08,
    criticalThreshold: 0.12,
  },
  {
    slug: 'missed_service_rate',
    name: 'Missed Service Rate',
    category: 'operations',
    definition: 'Percentage of scheduled services that were not completed as planned.',
    calculationNotes: 'COUNT(missed) / COUNT(scheduled) for services with scheduled_date in period.',
    grain: 'Weekly rollup',
    filters: ['date_range', 'market', 'branch', 'route'],
    primarySource: 'PestPac/Field Service',
    secondarySources: ['Workforce/HR (absence data)'],
    refreshCadence: 'Daily',
    owner: 'Operations - Director',
    reconciliationTarget: 'Missed count / scheduled count should match',
    dataQualityChecks: ['All scheduled services have final status', 'Reason code for missed services'],
    drillPath: '/kpi/missed_service_rate → by branch → by route → missed service list',
    format: 'percent',
    higherIsBetter: false,
    target: 0.02,
    warningThreshold: 0.04,
    criticalThreshold: 0.06,
  },
  {
    slug: 'avg_response_time_hours',
    name: 'Avg Response Time (Hours)',
    category: 'operations',
    definition: 'Average time from service request to service completion for on-demand requests.',
    calculationNotes: 'AVG(completed_date - request_date) in hours for on-demand service type.',
    grain: 'Weekly rollup',
    filters: ['date_range', 'market', 'branch', 'service_type'],
    primarySource: 'PestPac/Field Service',
    secondarySources: [],
    refreshCadence: 'Daily',
    owner: 'Operations - Director',
    reconciliationTarget: 'Manual calculation from service events should match',
    dataQualityChecks: ['Request timestamp captured', 'Completed timestamp captured', 'No negative response times'],
    drillPath: '/kpi/avg_response_time_hours → by branch → by priority → service event detail',
    format: 'number',
    higherIsBetter: false,
    target: 24,
    warningThreshold: 36,
    criticalThreshold: 48,
  },
  {
    slug: 'ar_aging',
    name: 'AR Aging',
    category: 'finance',
    definition: 'Total accounts receivable balance segmented by aging buckets (0-30, 31-60, 61-90, 90+ days).',
    calculationNotes: 'SUM(invoice.amount - payments) WHERE invoice.status = open GROUP BY days_since_due_date bucket.',
    grain: 'Daily snapshot',
    filters: ['market', 'branch', 'vertical', 'aging_bucket'],
    primarySource: 'Billing/ERP',
    secondarySources: [],
    refreshCadence: 'Daily (6am)',
    owner: 'Finance - AR Manager',
    reconciliationTarget: 'Sum of buckets = total AR balance',
    dataQualityChecks: ['All invoices have due date', 'Payment amounts valid', 'No orphaned payments'],
    drillPath: '/kpi/ar_aging → by bucket → by market → invoice list → invoice detail',
    format: 'currency',
    higherIsBetter: false,
  },
  {
    slug: 'dso',
    name: 'Days Sales Outstanding',
    category: 'finance',
    definition: 'Average number of days to collect payment after invoicing.',
    calculationNotes: '(AR Balance / Revenue_Last_30_Days) * 30.',
    grain: 'Monthly rollup',
    filters: ['market', 'branch', 'vertical'],
    primarySource: 'Billing/ERP',
    secondarySources: [],
    refreshCadence: 'Daily',
    owner: 'Finance - AR Manager',
    reconciliationTarget: 'AR balance and revenue figures should be consistent',
    dataQualityChecks: ['Revenue data complete', 'AR balance accurate'],
    drillPath: '/kpi/dso → trend over time → by market → collection actions',
    format: 'days',
    higherIsBetter: false,
    target: 35,
    warningThreshold: 45,
    criticalThreshold: 55,
  },
  {
    slug: 'capacity_utilization',
    name: 'Capacity Utilization',
    category: 'workforce',
    definition: 'Percentage of available technician hours that are scheduled/used.',
    calculationNotes: 'SUM(used_hours) / SUM(available_hours) across all technicians.',
    grain: 'Daily',
    filters: ['date_range', 'market', 'branch', 'route'],
    primarySource: 'Workforce/HR',
    secondarySources: ['PestPac/Field Service (actual time)'],
    refreshCadence: 'Every 4 hours',
    owner: 'Operations - Director',
    reconciliationTarget: 'Used hours from service events should match capacity system',
    dataQualityChecks: ['Available hours set for all techs', 'Time-on-site captured', 'No impossible utilization (>120%)'],
    drillPath: '/kpi/capacity_utilization → by branch → by technician → schedule detail',
    format: 'percent',
    higherIsBetter: true,
    target: 0.85,
    warningThreshold: 0.70,
    criticalThreshold: 0.60,
  },
  {
    slug: 'scheduling_pressure_index',
    name: 'Scheduling Pressure Index',
    category: 'workforce',
    definition: 'Composite index measuring scheduling strain based on utilization, overtime, and unfilled slots.',
    calculationNotes: '(utilization_score * 40 + overtime_score * 30 + unfilled_score * 30). Lower is better, 0-100 scale.',
    grain: 'Daily',
    filters: ['market', 'branch'],
    primarySource: 'Workforce/HR',
    secondarySources: ['PestPac/Field Service'],
    refreshCadence: 'Daily',
    owner: 'Operations - Director',
    reconciliationTarget: 'Component scores should sum correctly',
    dataQualityChecks: ['Overtime hours tracked', 'Schedule gaps identified', 'Capacity data current'],
    drillPath: '/kpi/scheduling_pressure_index → component breakdown → by branch → staffing detail',
    format: 'index',
    higherIsBetter: false,
    target: 30,
    warningThreshold: 50,
    criticalThreshold: 70,
  },
  {
    slug: 'crm_hygiene_score',
    name: 'CRM Hygiene Score',
    category: 'quality',
    definition: 'Score (0-100) measuring data quality in CRM: complete fields, current activities, valid stages.',
    calculationNotes: '(complete_fields_pct * 40 + recent_activity_pct * 30 + valid_stage_pct * 30).',
    grain: 'Daily snapshot',
    filters: ['market', 'branch', 'owner'],
    primarySource: 'CRM (Salesforce)',
    secondarySources: [],
    refreshCadence: 'Daily (5am)',
    owner: 'Sales Ops - Director',
    reconciliationTarget: 'Component metrics should calculate to score',
    dataQualityChecks: ['Required fields defined', 'Activity recency threshold set', 'Stage validation rules active'],
    drillPath: '/kpi/crm_hygiene_score → by component → by owner → opp/account issues list',
    format: 'index',
    higherIsBetter: true,
    target: 90,
    warningThreshold: 75,
    criticalThreshold: 60,
  },
  {
    slug: 'stalled_opps',
    name: 'Stalled Opportunities',
    category: 'sales',
    definition: 'Count and value of opportunities with no stage movement or activity in 14+ days.',
    calculationNotes: 'COUNT/SUM(amount) WHERE days_since_stage_change > 14 OR days_since_activity > 14.',
    grain: 'Daily snapshot',
    filters: ['market', 'branch', 'owner', 'stage'],
    primarySource: 'CRM (Salesforce)',
    secondarySources: [],
    refreshCadence: 'Daily',
    owner: 'Sales Ops - Director',
    reconciliationTarget: 'Stalled list count should match',
    dataQualityChecks: ['Stage change dates tracked', 'Activities logged with timestamps'],
    drillPath: '/kpi/stalled_opps → by owner → by stage → opportunity list → opp detail',
    format: 'currency',
    higherIsBetter: false,
  },
  {
    slug: 'retention_risk',
    name: 'Retention Risk',
    category: 'operations',
    definition: 'Count and contract value of accounts flagged as high retention risk.',
    calculationNotes: 'SUM(contract_value) WHERE retention_risk = high. Risk based on complaints, service issues, AR delinquency, declining activity.',
    grain: 'Daily snapshot',
    filters: ['market', 'branch', 'vertical', 'risk_level'],
    primarySource: 'PestPac/Field Service',
    secondarySources: ['CRM (complaints)', 'Billing/ERP (AR status)'],
    refreshCadence: 'Daily',
    owner: 'Operations - VP',
    reconciliationTarget: 'At-risk account list total should match',
    dataQualityChecks: ['Risk scoring model validated', 'All data inputs current', 'Thresholds calibrated'],
    drillPath: '/kpi/retention_risk → by risk factor → by market → account list → account detail',
    format: 'currency',
    higherIsBetter: false,
  },
  {
    slug: 'complaint_rate',
    name: 'Complaint Rate',
    category: 'quality',
    definition: 'Number of complaints per 1,000 service events.',
    calculationNotes: '(COUNT(complaints) / COUNT(service_events)) * 1000.',
    grain: 'Monthly rollup',
    filters: ['date_range', 'market', 'branch', 'complaint_type'],
    primarySource: 'CRM (Complaints)',
    secondarySources: ['PestPac/Field Service (service count)'],
    refreshCadence: 'Daily',
    owner: 'Customer Experience - Director',
    reconciliationTarget: 'Complaint count / service count * 1000 should match',
    dataQualityChecks: ['All complaints categorized', 'Service events counted correctly', 'Date ranges aligned'],
    drillPath: '/kpi/complaint_rate → by type → by branch → complaint list → account detail',
    format: 'number',
    higherIsBetter: false,
    target: 5,
    warningThreshold: 8,
    criticalThreshold: 12,
  },
  {
    slug: 'nrr',
    name: 'Net Revenue Retention',
    category: 'revenue',
    definition: 'Revenue from existing customers this period vs same customers last period, including expansion and churn.',
    calculationNotes: '(Starting_Revenue + Expansion - Contraction - Churn) / Starting_Revenue.',
    grain: 'Monthly rollup',
    filters: ['market', 'vertical'],
    primarySource: 'Billing/ERP',
    secondarySources: ['CRM (account changes)'],
    refreshCadence: 'Monthly (1st of month)',
    owner: 'Finance - FP&A',
    reconciliationTarget: 'Components should sum to NRR calculation',
    dataQualityChecks: ['Cohort tracking accurate', 'Expansion/contraction categorized', 'Churn reasons captured'],
    drillPath: '/kpi/nrr → component breakdown → by market → churned accounts list',
    format: 'percent',
    higherIsBetter: true,
    target: 1.05,
    warningThreshold: 0.98,
    criticalThreshold: 0.95,
  },
  {
    slug: 'margin_proxy',
    name: 'Margin Proxy',
    category: 'finance',
    definition: 'Estimated gross margin based on revenue minus estimated service cost (labor + materials).',
    calculationNotes: '(Revenue - (Labor_Hours * Avg_Cost + Material_Estimate)) / Revenue.',
    grain: 'Monthly rollup',
    filters: ['market', 'branch', 'vertical'],
    primarySource: 'Billing/ERP',
    secondarySources: ['Workforce/HR (labor cost)', 'PestPac (materials)'],
    refreshCadence: 'Weekly',
    owner: 'Finance - Controller',
    reconciliationTarget: 'Labor hours from workforce should match',
    dataQualityChecks: ['Labor rates current', 'Material costs estimated', 'Revenue allocated correctly'],
    drillPath: '/kpi/margin_proxy → cost breakdown → by market → by service type',
    format: 'percent',
    higherIsBetter: true,
    target: 0.45,
    warningThreshold: 0.38,
    criticalThreshold: 0.32,
  },
]

export const getKPIBySlug = (slug: string): KPIDefinition | undefined => {
  return KPI_DICTIONARY.find(kpi => kpi.slug === slug)
}

export const getKPIsByCategory = (category: string): KPIDefinition[] => {
  return KPI_DICTIONARY.filter(kpi => kpi.category === category)
}

export const TOP_10_KPIS = [
  'revenue_mtd',
  'variance_to_target_mtd',
  'pipeline_30_60_90',
  'win_rate',
  'forecast_revenue_8w',
  'service_risk_index',
  'callback_rate',
  'ar_aging',
  'capacity_utilization',
  'crm_hygiene_score',
]

export const DATA_SOURCES: { name: string; system: string; description: string }[] = [
  { name: 'CRM', system: 'Salesforce', description: 'Opportunities, Activities, Accounts, Contacts' },
  { name: 'Billing/ERP', system: 'SAP/Oracle', description: 'Invoices, Payments, AR, Revenue' },
  { name: 'Field Service', system: 'PestPac', description: 'Service Events, Routes, Callbacks, Materials' },
  { name: 'Workforce/HR', system: 'Workday', description: 'Technicians, Capacity, Scheduling, Labor Costs' },
]
