/**
 * Start Packet Generator Utilities
 *
 * Functions for generating start packet data and email content
 */

import type {
  SalesforceQuoteDraft,
  StartPacket,
  StartPacketStatus,
  OpsEmailNotification,
  ParsedService,
} from '@/types/salesforce-quote'

/**
 * Generate a unique ID for start packets
 */
export function generateStartPacketId(): string {
  const timestamp = Date.now().toString(36)
  const random = Math.random().toString(36).substring(2, 8)
  return `SP-${timestamp}-${random}`.toUpperCase()
}

/**
 * Create a new StartPacket from parsed draft data
 */
export function createStartPacket(
  draft: SalesforceQuoteDraft,
  overrides?: Partial<StartPacket>
): StartPacket {
  const now = new Date().toISOString()

  return {
    ...draft,
    id: generateStartPacketId(),
    createdAt: now,
    updatedAt: now,
    status: 'draft' as StartPacketStatus,
    pdfStorageKey: null,
    emailSent: false,
    emailSentAt: null,
    ...overrides,
  }
}

/**
 * Get frequency label from services
 */
export function getFrequencyLabel(services: ParsedService[]): string {
  if (!services || services.length === 0) return 'Monthly (12x/year)'

  const maxServicesPerYear = Math.max(...services.map(s => s.servicesPerYear || 0))

  if (maxServicesPerYear >= 24) return 'Semi-Monthly (24x/year)'
  if (maxServicesPerYear >= 12) return 'Monthly (12x/year)'
  if (maxServicesPerYear >= 6) return 'Bi-Monthly (6x/year)'
  if (maxServicesPerYear >= 4) return 'Quarterly (4x/year)'
  if (maxServicesPerYear >= 2) return 'Semi-Annual (2x/year)'
  return 'Annual (1x/year)'
}

/**
 * Format currency value
 */
export function formatCurrency(value: number | null | undefined): string {
  if (!value) return '$0.00'
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(value)
}

/**
 * Generate email notification data from start packet
 */
export function generateOpsEmailNotification(
  packet: StartPacket,
  customRecipients?: string[]
): OpsEmailNotification {
  return {
    to: customRecipients || [],
    subject: `Re: Onboarding Report - ${packet.accountName || 'New Account'} -- ${packet.contactName || 'Customer'}`,
    body: generateEmailBody(packet),
    startPacketId: packet.id,
    accountName: packet.accountName || '',
    contactName: packet.contactName || '',
    serviceAddress: packet.serviceAddress || '',
    initialPrice: packet.combinedInitialTotal || 0,
    monthlyPrice: packet.servicesMonthlyTotal || 0,
    coveredPests: packet.coveredPests || [],
    maintenanceScope: packet.maintenanceScopeDescription || '',
    frequency: getFrequencyLabel(packet.services),
    specialNotes: packet.initialServiceDescription || '',
  }
}

/**
 * Generate email body from start packet data
 */
export function generateEmailBody(packet: StartPacket): string {
  const coveredPestsStr = Array.isArray(packet.coveredPests)
    ? packet.coveredPests.join(', ')
    : packet.coveredPests || 'N/A'

  return `Team,

Please find the attached start packet for the location below.

Service Details
• Frequency: ${getFrequencyLabel(packet.services)}
• Covered Pests: ${coveredPestsStr}
• Scope: ${packet.maintenanceScopeDescription || 'N/A'}
• Treatment Notes: ${packet.initialServiceDescription || 'N/A'}

Commercials
• Total Initial: ${formatCurrency(packet.combinedInitialTotal)}
• Monthly: ${formatCurrency(packet.servicesMonthlyTotal)}/month

Account Details
• Customer: ${packet.accountName || 'N/A'}
• Service Address: ${packet.serviceAddress || 'N/A'}
• Billing Email: ${packet.billingEmail || packet.contactEmail || 'N/A'}
• POC: ${packet.contactName || 'N/A'}

---
This email was generated by the Rentokil BI Start Packet System.
Start Packet ID: ${packet.id}
`
}

/**
 * Generate equipment summary string
 */
export function generateEquipmentSummary(packet: StartPacket): string {
  const parts: string[] = []

  if (packet.equipment?.multCatchQty > 0) {
    parts.push(`${packet.equipment.multCatchQty} MRT`)
  }
  if (packet.equipment?.rbsQty > 0) {
    parts.push(`${packet.equipment.rbsQty} RBS`)
  }
  if (packet.equipment?.iltQty > 0) {
    parts.push(`${packet.equipment.iltQty} ILT`)
  }

  return parts.length > 0 ? parts.join(', ') : 'No equipment specified'
}

/**
 * Generate services summary string
 */
export function generateServicesSummary(packet: StartPacket): string {
  if (!packet.services || packet.services.length === 0) {
    return 'No services specified'
  }

  return packet.services
    .map(s => `${s.serviceName} (${s.frequencyLabel})`)
    .join(', ')
}

/**
 * Calculate annual contract value
 */
export function calculateAnnualValue(packet: StartPacket): number {
  const initial = packet.combinedInitialTotal || 0
  const monthly = packet.servicesMonthlyTotal || 0
  return initial + (monthly * 12)
}

/**
 * Update start packet status
 */
export function updatePacketStatus(
  packet: StartPacket,
  newStatus: StartPacketStatus
): StartPacket {
  return {
    ...packet,
    status: newStatus,
    updatedAt: new Date().toISOString(),
  }
}

/**
 * Mark packet as email sent
 */
export function markEmailSent(packet: StartPacket): StartPacket {
  return {
    ...packet,
    emailSent: true,
    emailSentAt: new Date().toISOString(),
    status: 'pending_ops',
    updatedAt: new Date().toISOString(),
  }
}

/**
 * Validate start packet has required fields for submission
 */
export function validatePacketForSubmission(packet: StartPacket): {
  isValid: boolean
  errors: string[]
} {
  const errors: string[] = []

  if (!packet.accountName) {
    errors.push('Account name is required')
  }
  if (!packet.serviceAddress) {
    errors.push('Service address is required')
  }
  if (!packet.combinedInitialTotal && !packet.servicesMonthlyTotal) {
    errors.push('At least one pricing field is required')
  }

  return {
    isValid: errors.length === 0,
    errors,
  }
}

/**
 * Get status display info
 */
export function getStatusDisplay(status: StartPacketStatus): {
  label: string
  color: string
  bgColor: string
} {
  const statusMap: Record<StartPacketStatus, { label: string; color: string; bgColor: string }> = {
    draft: { label: 'Draft', color: 'text-gray-700', bgColor: 'bg-gray-100' },
    pending_ops: { label: 'Pending Ops', color: 'text-yellow-700', bgColor: 'bg-yellow-100' },
    ops_reviewing: { label: 'Ops Reviewing', color: 'text-blue-700', bgColor: 'bg-blue-100' },
    approved: { label: 'Approved', color: 'text-green-700', bgColor: 'bg-green-100' },
    rejected: { label: 'Rejected', color: 'text-red-700', bgColor: 'bg-red-100' },
    completed: { label: 'Completed', color: 'text-purple-700', bgColor: 'bg-purple-100' },
  }

  return statusMap[status] || statusMap.draft
}
