'use client'

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  Mail,
  Send,
  FileText,
  User,
  MapPin,
  DollarSign,
  Bug,
  Package,
  Wrench,
  CheckCircle,
  AlertCircle,
  Loader2,
  X,
  Eye,
  Copy,
  Check,
} from 'lucide-react'
import type {
  SalesforceQuoteDraft,
  StartPacket,
  OpsEmailNotification,
  OpsEmailResponse,
  ParsedService,
} from '@/types/salesforce-quote'

interface StartPacketPreviewProps {
  draft: SalesforceQuoteDraft
  formData: {
    accountName: string
    serviceAddress: string
    salesRepsInvolved: string
    initialJobPrice: string
    maintenancePrice: string
    serviceType: string
    frequency: string
  }
  onSubmit: (packet: StartPacket, emailResult: OpsEmailResponse) => void
  onCancel: () => void
  isOpen: boolean
}

export function StartPacketPreview({
  draft,
  formData,
  onSubmit,
  onCancel,
  isOpen,
}: StartPacketPreviewProps) {
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitStatus, setSubmitStatus] = useState<'idle' | 'creating' | 'sending' | 'success' | 'error'>('idle')
  const [error, setError] = useState<string | null>(null)
  const [emailPreview, setEmailPreview] = useState<OpsEmailResponse['emailPreview'] | null>(null)
  const [showEmailPreview, setShowEmailPreview] = useState(false)
  const [copied, setCopied] = useState(false)

  if (!isOpen) return null

  const formatCurrency = (value: number | string | null | undefined) => {
    const num = typeof value === 'string' ? parseFloat(value) : value
    if (!num) return '$0.00'
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(num)
  }

  // Determine max frequency from services
  const getMaxFrequency = (services: ParsedService[]): string => {
    if (!services || services.length === 0) return formData.frequency || '12'
    const maxServicesPerYear = Math.max(...services.map(s => s.servicesPerYear || 0))
    if (maxServicesPerYear >= 24) return 'Semi-Monthly (24x/year)'
    if (maxServicesPerYear >= 12) return 'Monthly (12x/year)'
    if (maxServicesPerYear >= 6) return 'Bi-Monthly (6x/year)'
    if (maxServicesPerYear >= 4) return 'Quarterly (4x/year)'
    if (maxServicesPerYear >= 2) return 'Semi-Annual (2x/year)'
    return 'Annual (1x/year)'
  }

  const handleSubmit = async () => {
    setIsSubmitting(true)
    setSubmitStatus('creating')
    setError(null)

    try {
      // Step 1: Create start packet
      const packetData = {
        ...draft,
        accountName: formData.accountName || draft.accountName,
        serviceAddress: formData.serviceAddress || draft.serviceAddress,
        combinedInitialTotal: parseFloat(formData.initialJobPrice) || draft.combinedInitialTotal,
        servicesMonthlyTotal: parseFloat(formData.maintenancePrice) || draft.servicesMonthlyTotal,
      }

      const createResponse = await fetch('/api/start-packet', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(packetData),
      })

      if (!createResponse.ok) {
        const errorData = await createResponse.json()
        throw new Error(errorData.message || 'Failed to create start packet')
      }

      const { startPacket } = await createResponse.json()

      // Step 2: Send Ops notification
      setSubmitStatus('sending')

      const emailNotification: OpsEmailNotification = {
        to: [],  // Use default recipients from API
        subject: `Re: Onboarding Report - ${formData.accountName || draft.accountName} -- ${draft.contactName || 'Customer'}`,
        body: '',  // Generated by API
        startPacketId: startPacket.id,
        accountName: formData.accountName || draft.accountName || '',
        contactName: draft.contactName || '',
        serviceAddress: formData.serviceAddress || draft.serviceAddress || '',
        initialPrice: parseFloat(formData.initialJobPrice) || draft.combinedInitialTotal || 0,
        monthlyPrice: parseFloat(formData.maintenancePrice) || draft.servicesMonthlyTotal || 0,
        coveredPests: draft.coveredPests || [],
        maintenanceScope: draft.maintenanceScopeDescription || '',
        frequency: getMaxFrequency(draft.services),
        specialNotes: draft.initialServiceDescription || '',
      }

      const emailResponse = await fetch('/api/notifications/ops-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(emailNotification),
      })

      if (!emailResponse.ok) {
        const errorData = await emailResponse.json()
        throw new Error(errorData.message || 'Failed to send notification')
      }

      const emailResult: OpsEmailResponse = await emailResponse.json()
      setEmailPreview(emailResult.emailPreview)
      setSubmitStatus('success')

      // Notify parent component
      onSubmit(startPacket, emailResult)
    } catch (err) {
      console.error('[StartPacketPreview] Submit error:', err)
      setError(err instanceof Error ? err.message : 'An error occurred')
      setSubmitStatus('error')
    } finally {
      setIsSubmitting(false)
    }
  }

  const copyEmailToClipboard = async () => {
    if (!emailPreview) return
    const text = `To: ${emailPreview.to}\nSubject: ${emailPreview.subject}\n\n${emailPreview.body}`
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const hasEquipment = draft.equipment && (
    draft.equipment.multCatchQty > 0 ||
    draft.equipment.rbsQty > 0 ||
    draft.equipment.iltQty > 0
  )

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-900 rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="sticky top-0 bg-white dark:bg-gray-900 border-b dark:border-gray-800 p-4 flex items-center justify-between z-10">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 bg-green-100 dark:bg-green-900 rounded-lg flex items-center justify-center">
              <FileText className="h-5 w-5 text-green-600 dark:text-green-400" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
                Start Packet Preview
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Review before sending to Operations
              </p>
            </div>
          </div>
          <Button variant="ghost" size="icon" onClick={onCancel} disabled={isSubmitting}>
            <X className="h-5 w-5" />
          </Button>
        </div>

        {/* Content */}
        <div className="p-4 space-y-4">
          {/* Status Message */}
          {submitStatus === 'success' && (
            <div className="bg-green-50 dark:bg-green-950/30 border border-green-200 dark:border-green-800 rounded-lg p-4">
              <div className="flex items-center gap-2 text-green-800 dark:text-green-200">
                <CheckCircle className="h-5 w-5" />
                <span className="font-medium">Start Packet Submitted Successfully!</span>
              </div>
              <p className="mt-1 text-sm text-green-700 dark:text-green-300">
                Operations has been notified and will begin processing.
              </p>
            </div>
          )}

          {error && (
            <div className="bg-red-50 dark:bg-red-950/30 border border-red-200 dark:border-red-800 rounded-lg p-4">
              <div className="flex items-center gap-2 text-red-800 dark:text-red-200">
                <AlertCircle className="h-5 w-5" />
                <span className="font-medium">Error</span>
              </div>
              <p className="mt-1 text-sm text-red-700 dark:text-red-300">{error}</p>
            </div>
          )}

          {/* Account Info Card */}
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm flex items-center gap-2">
                <User className="h-4 w-4 text-gray-500" />
                Account Information
              </CardTitle>
            </CardHeader>
            <CardContent className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <span className="text-gray-500 dark:text-gray-400">Customer</span>
                <p className="font-medium">{formData.accountName || draft.accountName || 'N/A'}</p>
              </div>
              <div>
                <span className="text-gray-500 dark:text-gray-400">Contact</span>
                <p className="font-medium">{draft.contactName || 'N/A'}</p>
              </div>
              <div className="col-span-2">
                <span className="text-gray-500 dark:text-gray-400 flex items-center gap-1">
                  <MapPin className="h-3 w-3" /> Service Address
                </span>
                <p className="font-medium">{formData.serviceAddress || draft.serviceAddress || 'N/A'}</p>
              </div>
              {draft.contactEmail && (
                <div>
                  <span className="text-gray-500 dark:text-gray-400">Email</span>
                  <p className="font-medium">{draft.contactEmail}</p>
                </div>
              )}
              {formData.salesRepsInvolved && (
                <div>
                  <span className="text-gray-500 dark:text-gray-400">Sales Rep</span>
                  <p className="font-medium">{formData.salesRepsInvolved}</p>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Pricing Card */}
          <Card>
            <CardHeader className="pb-2">
              <CardTitle className="text-sm flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-gray-500" />
                Pricing Summary
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-3 gap-4 text-center">
                <div className="bg-blue-50 dark:bg-blue-950/30 rounded-lg p-3">
                  <p className="text-xs text-blue-600 dark:text-blue-400 uppercase font-medium">Initial</p>
                  <p className="text-lg font-bold text-blue-900 dark:text-blue-100">
                    {formatCurrency(formData.initialJobPrice || draft.combinedInitialTotal)}
                  </p>
                </div>
                <div className="bg-green-50 dark:bg-green-950/30 rounded-lg p-3">
                  <p className="text-xs text-green-600 dark:text-green-400 uppercase font-medium">Monthly</p>
                  <p className="text-lg font-bold text-green-900 dark:text-green-100">
                    {formatCurrency(formData.maintenancePrice || draft.servicesMonthlyTotal)}
                  </p>
                </div>
                <div className="bg-purple-50 dark:bg-purple-950/30 rounded-lg p-3">
                  <p className="text-xs text-purple-600 dark:text-purple-400 uppercase font-medium">Annual Value</p>
                  <p className="text-lg font-bold text-purple-900 dark:text-purple-100">
                    {formatCurrency(
                      (parseFloat(formData.initialJobPrice) || draft.combinedInitialTotal || 0) +
                      ((parseFloat(formData.maintenancePrice) || draft.servicesMonthlyTotal || 0) * 12)
                    )}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Equipment & Services */}
          {(hasEquipment || draft.services?.length > 0) && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Package className="h-4 w-4 text-gray-500" />
                  Equipment & Services
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {hasEquipment && (
                  <div>
                    <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-medium mb-1">Equipment</p>
                    <div className="flex flex-wrap gap-2">
                      {draft.equipment.multCatchQty > 0 && (
                        <Badge variant="outline">
                          {draft.equipment.multCatchQty} MRT
                        </Badge>
                      )}
                      {draft.equipment.rbsQty > 0 && (
                        <Badge variant="outline">
                          {draft.equipment.rbsQty} RBS
                        </Badge>
                      )}
                      {draft.equipment.iltQty > 0 && (
                        <Badge variant="outline">
                          {draft.equipment.iltQty} ILT
                        </Badge>
                      )}
                    </div>
                  </div>
                )}
                {draft.services?.length > 0 && (
                  <div>
                    <p className="text-xs text-gray-500 dark:text-gray-400 uppercase font-medium mb-1">Services</p>
                    <div className="space-y-1">
                      {draft.services.map((svc, idx) => (
                        <div key={idx} className="flex items-center justify-between text-sm">
                          <span className="flex items-center gap-2">
                            <Wrench className="h-3 w-3 text-gray-400" />
                            {svc.serviceName}
                          </span>
                          <Badge variant="secondary" className="text-xs">
                            {svc.frequencyLabel}
                          </Badge>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Covered Pests */}
          {draft.coveredPests?.length > 0 && (
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Bug className="h-4 w-4 text-gray-500" />
                  Covered Pests
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-1">
                  {draft.coveredPests.map((pest, idx) => (
                    <Badge key={idx} variant="outline" className="text-xs">
                      {pest}
                    </Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Email Preview (after submission) */}
          {emailPreview && (
            <Card className="border-blue-200 dark:border-blue-800">
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Mail className="h-4 w-4 text-blue-500" />
                    Email Notification Preview
                  </CardTitle>
                  <div className="flex gap-2">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setShowEmailPreview(!showEmailPreview)}
                    >
                      <Eye className="h-4 w-4 mr-1" />
                      {showEmailPreview ? 'Hide' : 'View'}
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={copyEmailToClipboard}
                    >
                      {copied ? (
                        <Check className="h-4 w-4 mr-1 text-green-500" />
                      ) : (
                        <Copy className="h-4 w-4 mr-1" />
                      )}
                      {copied ? 'Copied!' : 'Copy'}
                    </Button>
                  </div>
                </div>
                <CardDescription>
                  Sent to: {emailPreview.to}
                </CardDescription>
              </CardHeader>
              {showEmailPreview && (
                <CardContent>
                  <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-3 space-y-2 text-sm">
                    <div>
                      <span className="text-gray-500 dark:text-gray-400">Subject: </span>
                      <span className="font-medium">{emailPreview.subject}</span>
                    </div>
                    <div className="border-t dark:border-gray-700 pt-2">
                      <pre className="whitespace-pre-wrap text-xs font-mono text-gray-600 dark:text-gray-300">
                        {emailPreview.body}
                      </pre>
                    </div>
                  </div>
                </CardContent>
              )}
            </Card>
          )}
        </div>

        {/* Footer Actions */}
        <div className="sticky bottom-0 bg-white dark:bg-gray-900 border-t dark:border-gray-800 p-4 flex justify-end gap-3">
          {submitStatus === 'success' ? (
            <Button onClick={onCancel} className="bg-green-600 hover:bg-green-700">
              <CheckCircle className="h-4 w-4 mr-2" />
              Done
            </Button>
          ) : (
            <>
              <Button variant="outline" onClick={onCancel} disabled={isSubmitting}>
                Cancel
              </Button>
              <Button
                onClick={handleSubmit}
                disabled={isSubmitting}
                className="bg-green-600 hover:bg-green-700"
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    {submitStatus === 'creating' ? 'Creating Packet...' : 'Sending Email...'}
                  </>
                ) : (
                  <>
                    <Send className="h-4 w-4 mr-2" />
                    Submit & Notify Ops
                  </>
                )}
              </Button>
            </>
          )}
        </div>
      </div>
    </div>
  )
}
