import { NextRequest, NextResponse } from 'next/server'
import type { OpsEmailResponse, OpsEmailNotification } from '@/types/salesforce-quote'

// Environment configuration
const EMAIL_MODE = process.env.NEXT_PUBLIC_EMAIL_MODE || 'simulation'
const OPS_EMAIL_RECIPIENTS = process.env.OPS_EMAIL_RECIPIENTS ||
  'midwestmarketsalesentry@rentokil.com,brad.hudson@prestox.com'

/**
 * Generate email body from start packet data
 */
function generateEmailBody(data: OpsEmailNotification): string {
  const formatCurrency = (value: number | null | undefined) => {
    if (!value) return '$0.00'
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(value)
  }

  return `Team,

Please find the attached start packet for the location below.

Service Details
• Frequency: ${data.frequency || '12'}
• Covered Pests: ${Array.isArray(data.coveredPests) ? data.coveredPests.join(', ') : data.coveredPests || 'N/A'}
• Scope: ${data.maintenanceScope || 'N/A'}
• Treatment Notes: ${data.specialNotes || 'N/A'}

Commercials
• Total Initial: ${formatCurrency(data.initialPrice)}
• Monthly: ${formatCurrency(data.monthlyPrice)}/month

Account Details
• Customer: ${data.accountName}
• Service Address: ${data.serviceAddress}
• Billing Email: ${data.accountName || 'N/A'}
• POC: ${data.contactName}

---
This email was generated by the Rentokil BI Start Packet System.
Start Packet ID: ${data.startPacketId}
`
}

/**
 * POST /api/notifications/ops-email
 * Send or simulate Operations email notification
 */
export async function POST(request: NextRequest): Promise<NextResponse<OpsEmailResponse>> {
  try {
    const data: OpsEmailNotification = await request.json()

    // Validate required fields
    if (!data.accountName) {
      return NextResponse.json(
        {
          success: false,
          emailPreview: { to: '', subject: '', body: '' },
          message: 'Account name is required',
          actualEmailSent: false,
        },
        { status: 400 }
      )
    }

    const recipients = data.to?.length ? data.to.join(', ') : OPS_EMAIL_RECIPIENTS
    const subject = data.subject || `Re: Onboarding Report - ${data.accountName} -- ${data.contactName || 'Customer'}`
    const body = data.body || generateEmailBody(data)

    const emailPreview = {
      to: recipients,
      subject,
      body,
    }

    // Check if we should send a real email
    const isLiveMode = EMAIL_MODE === 'live'

    if (isLiveMode) {
      // In live mode, we would integrate with an email service
      // For now, we'll check if Resend API key is configured
      const resendApiKey = process.env.RESEND_API_KEY

      if (resendApiKey) {
        try {
          // TODO: Implement actual email sending with Resend
          // const response = await resend.emails.send({
          //   from: 'noreply@rentokil.com',
          //   to: recipients.split(',').map(e => e.trim()),
          //   subject,
          //   text: body,
          // })

          console.log('[Ops Email] Would send real email via Resend:', {
            to: recipients,
            subject,
            bodyLength: body.length,
          })

          // For now, fall through to simulation
        } catch (emailError) {
          console.error('[Ops Email] Failed to send real email:', emailError)
          // Fall through to simulation
        }
      } else {
        console.warn('[Ops Email] Live mode enabled but RESEND_API_KEY not configured')
      }
    }

    // Simulation mode - log and return preview
    console.log('[Ops Email] Notification sent (simulation):', {
      to: recipients,
      subject,
      startPacketId: data.startPacketId,
      mode: EMAIL_MODE,
    })

    return NextResponse.json({
      success: true,
      emailPreview,
      message: isLiveMode
        ? 'Operations notification sent successfully'
        : 'Operations notification simulated (demo mode)',
      actualEmailSent: false, // Set to true when real email integration is complete
    })
  } catch (error) {
    console.error('[Ops Email] Error:', error)
    return NextResponse.json(
      {
        success: false,
        emailPreview: { to: '', subject: '', body: '' },
        message: error instanceof Error ? error.message : 'Failed to send notification',
        actualEmailSent: false,
      },
      { status: 500 }
    )
  }
}
